name: wage_etl_services
services:
  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${WAGE_ETL_DB__USER}
      POSTGRES_PASSWORD: ${WAGE_ETL_DB__PASSWORD}
      POSTGRES_DB: ${WAGE_ETL_DB__NAME}
    ports:
      - "${WAGE_ETL_DB__PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${WAGE_ETL_DB__USER} -d ${WAGE_ETL_DB__NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - wage_etl_net

  flyway:
    image: flyway/flyway:11
    container_name: flyway
    depends_on:
      db:
        condition: service_healthy
    command: [
      "-url=jdbc:postgresql://db:5432/${WAGE_ETL_DB__NAME}",
      "-user=${WAGE_ETL_DB__USER}",
      "-password=${WAGE_ETL_DB__PASSWORD}",
      "migrate"
    ]
    volumes:
      - ./sql:/flyway/sql
    networks:
      - wage_etl_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - wage_etl_net

volumes:
  db_data:
  pgadmin_data:

networks:
  wage_etl_net:
    driver: bridge